services:
  - type: web
    name: movie-stream-php
    env: docker
    plan: free
    repo: https://github.com/Appureddy143/movie-stream-render-site-
    branch: main
    dockerContext: .
    dockerfilePath: Dockerfile
    region: oregon
    healthCheckPath: /
